name: Go Workflow

on: [push]

jobs:
  setup:
    name: Setup Go Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1' # Specify the Go version to match your go.mod file

  test:
    name: Run Go Tests
    needs: setup # This job runs after the setup job completes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1' 

      - name: Run Go Test
        run: go test ./...
        working-directory: ./5-code-quality/go

  dispatch:
    name: Dispatch event
    needs: test
    runs-on: ubuntu-latest # Specify where this job should run
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            event-type: my-event
            client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
