# This is a basic workflow to experiment with repo dispatches
# go.yml dispatches an event -- NOTE -- go.yml is currently configured to trigger a DIFFERENT repo
# hence this workflow will not be triggered

name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}